### PR TITLE
ADD: Interface to the SPRAL linear solver

### LINKED ISSUE #335: Feature request: IPOPT support for GPU based linear solvers
I wanted to ask if it is possible to provide support for GPU based linear solvers such as cuSPARSE or cuSolver.

### LINKED ISSUE #413: Request: SPRAL support?
Hello,

I'm guessing you've seen (or been a coauthor on) this comparison of various linear solvers in Ipopt: https://arxiv.org/pdf/1909.08104.pdf The paper notes "Prior to this study, SPRAL was not available within Ipopt. This is surprising due to its stability-preserving features and heterogeneous parallelization capabilities." Ultimately, the paper concludes that SPRAL is the best free solver for difficult problems. I'd add that it would be valuable to have another freely-licensed solver beyond MUMPS.

In the current Ipopt release, 3.13.2, [SPRAL](https://github.com/ralna/spral) remains unavailable (which makes sense! I'm sure it's a bunch of work to add a solver). Would it be possible to add SPRAL support to Ipopt?

Thanks!

### PR DESCRIPTION
**Pull request by tasseff**
This would close #413 and close #335. We have [a report written here](https://arxiv.org/pdf/1909.08104.pdf), a [fork of SPRAL with some minor edits here](https://github.com/lanl-ansi/spral), and a [fork of Ipopt with the interface here](https://github.com/lanl-ansi/Ipopt). One concern is ensuring the [extra license text](https://github.com/lanl-ansi/Ipopt/blob/master/LICENSE.md) we have had to add to open-source our project is somehow incorporated into the master repository. Please let me know what I can do to clean up the interface, as I'm sure there's some stuff that I may have missed.

### CODE REVIEW

**Comment by svigerske** [comment]
Yeah, about that license text. So what is that necessary for?
The big source files with the interface that you add say "This code is published under the Eclipse Public License."

It may be confusing if there are two LICENSE files in the main directory, specifying two different licenses for the whole Ipopt, but nothing in the docu mention any dual-licensing and every source file says EPL.

If there is a problem in adding the interface under EPL, then adding it under BSD could be an option, I believe.

**Comment by tasseff** [comment]
The files I used as templates when writing the new interface were indeed previous files in Ipopt licensed under the EPL, so it would probably make sense to keep them as EPL-licensed since they're derivative works. I'm not sure if it's necessary to include the new license text, but I'm not a legal expert. Is the EPL compatible with the BSD 3-ish license I linked? I imagine since the BSD 3 license is so permissive, this shouldn't be an issue, but let me try to obtain more guidance from the legal counsel at LANL.

**Comment by svigerske** [comment]
If the interface files can be published under EPL, then the other parts, which are mainly smaller patches to existing files, should also not have to change license or get an additional different license. But I'm not a legal expert, too.

I managed to compile a Spral library (had to disable OpenMP and I don't have NVCC) and get that used by Ipopt.

So, I don't think that there is much left to do. The license thing needs to be clarified. I would leave out the COMPILE.md, as that is very specific to one setup and mostly duplicates what is in the documentation.

**Comment by tkralphs** [comment]
I just want to point out that the CLA, which was signed for this PR, requires that any contribution to a project be under the same license.

**Comment by svigerske** [comment]
@tasseff Did you get any feedback from LANL on the license issue? Could we merge this without adding LICENSE.md?

**Comment by tasseff** [comment]
@svigerske, I still have not received any firm guidance. However, considering that (as you pointed out) the relevant modified files were originally published under the (more restrictive) EPL license, it would make sense that our LICENSE.md file would not be required in this pull request. Nonetheless, let me try to get another update from the relevant people at LANL to ensure this. I'm extremely sorry for the long delay.

**Comment by tasseff** [comment]
I apologize, but I'm now being told by our intellectual property team that I need to remove our Ipopt fork until they've sorted through any license incompatibility issues. I am hoping this will be resolved soon. I will close this pull request for the time being.

**Comment by tasseff** [comment]
Update: I've been given approval to release our contributions under the EPL-2.0. I will make a new fork and fix this pull request within the next few days.

**Comment by svigerske** [comment]
Good news. Would be nice if you could base your work on the branch `devel`.

**Pull request closed without merging**
